-- Wick's UI
-- Core/Layout.lua: the layout the interface starts with.
--
-- Wick's own setup, baked from a played profile: every setting and every
-- frame's position. It is laid over the modules' defaults once they are
-- all registered, so a new profile starts here and "Reset" comes back
-- here. Only keys the defaults know are taken (the movers and the per
-- style sizes excepted), so a setting that has since gone is dropped
-- rather than carried along. The game's scale is left out: it belongs to
-- the screen, and the first-run setup asks for it.
--
-- Regenerate with WickSuite/tools/bake-wicksui-layout.py.

local ADDON, ns = ...

local LAYOUT = {
    actionbars = {
        abbreviate = true,
        autoRank = true,
        bars = {
            [1] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = true,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 1,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,40",
                showCount = true,
                showGrid = true,
                showHotkey = true,
                showMacro = true,
                size = 40,
                spacing = 2,
                visibility = "show",
            },
            [2] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = false,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 2,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,76",
                showCount = true,
                showGrid = true,
                showHotkey = true,
                showMacro = true,
                size = 38,
                spacing = 6,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [3] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = true,
                flyout = "LEFT",
                globalFade = false,
                growth = "TOPRIGHT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 1,
                perRow = 12,
                point = "RIGHT,UIParent,RIGHT,-4,0",
                showCount = true,
                showGrid = true,
                showHotkey = true,
                showMacro = true,
                size = 40,
                spacing = 2,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [4] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = true,
                flyout = "UP",
                globalFade = false,
                growth = "TOPLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 1,
                perRow = 6,
                point = "RIGHT,UIParent,RIGHT,-40,0",
                showCount = true,
                showGrid = true,
                showHotkey = true,
                showMacro = true,
                size = 40,
                spacing = 2,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [5] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = true,
                flyout = "UP",
                globalFade = false,
                growth = "TOPLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 1,
                perRow = 6,
                point = "BOTTOM,UIParent,BOTTOM,0,112",
                showCount = true,
                showGrid = true,
                showHotkey = true,
                showMacro = true,
                size = 40,
                spacing = 2,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [6] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = true,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 1,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,76",
                showCount = true,
                showGrid = true,
                showHotkey = true,
                showMacro = true,
                size = 40,
                spacing = 2,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [7] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = false,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 2,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,112",
                showCount = true,
                showGrid = false,
                showHotkey = true,
                showMacro = true,
                size = 38,
                spacing = 6,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [8] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = false,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 2,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,148",
                showCount = true,
                showGrid = false,
                showHotkey = true,
                showMacro = true,
                size = 38,
                spacing = 6,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [9] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = false,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 2,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,184",
                showCount = true,
                showGrid = false,
                showHotkey = true,
                showMacro = true,
                size = 38,
                spacing = 6,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [10] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = false,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 2,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,220",
                showCount = true,
                showGrid = false,
                showHotkey = true,
                showMacro = true,
                size = 38,
                spacing = 6,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [13] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = false,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 2,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,148",
                showCount = true,
                showGrid = false,
                showHotkey = true,
                showMacro = true,
                size = 38,
                spacing = 6,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [14] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = false,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 2,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,148",
                showCount = true,
                showGrid = false,
                showHotkey = true,
                showMacro = true,
                size = 38,
                spacing = 6,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
            [15] = {
                alpha = 1,
                backdrop = false,
                buttons = 12,
                enable = false,
                flyout = "UP",
                globalFade = false,
                growth = "BOTTOMLEFT",
                height = 34,
                keepRatio = true,
                mouseover = false,
                mouseoverAlpha = 0,
                padding = 2,
                perRow = 12,
                point = "BOTTOM,UIParent,BOTTOM,0,148",
                showCount = true,
                showGrid = false,
                showHotkey = true,
                showMacro = true,
                size = 38,
                spacing = 6,
                visibility = "[overridebar][vehicleui][possessbar] hide; show",
            },
        },
        cooldownText = true,
        countSize = 14,
        enable = true,
        fadeAlpha = 0,
        fadeIn = "combat,target,casting,mouseover",
        font = "Wick",
        fontOutline = "OUTLINE",
        hotkeyColor = {
            [1] = 0.83,
            [2] = 0.78,
            [3] = 0.63,
            [4] = 1,
        },
        hotkeySize = 12,
        keyDown = true,
        lockBars = false,
        macroSize = 10,
        manaColor = {
            [1] = 0.35,
            [2] = 0.45,
            [3] = 1,
            [4] = 1,
        },
        matchedGame = true,
        pet = {
            alpha = 1,
            backdrop = false,
            buttons = 10,
            enable = true,
            flyout = "UP",
            globalFade = false,
            growth = "BOTTOMLEFT",
            height = 34,
            keepRatio = true,
            mouseover = false,
            mouseoverAlpha = 0,
            padding = 2,
            perRow = 6,
            point = "BOTTOMRIGHT,UIParent,BOTTOM,216,152",
            showCount = true,
            showGrid = false,
            showHotkey = true,
            showMacro = true,
            size = 28,
            spacing = 2,
            visibility = "[pet,novehicleui,nooverridebar,nopossessbar] show; hide",
        },
        procGlow = true,
        rangeColor = {
            [1] = 0.85,
            [2] = 0.2,
            [3] = 0.2,
            [4] = 1,
        },
        rangeColoring = "button",
        stance = {
            alpha = 1,
            backdrop = false,
            buttons = 10,
            enable = true,
            flyout = "UP",
            globalFade = false,
            growth = "BOTTOMLEFT",
            height = 34,
            keepRatio = true,
            mouseover = false,
            mouseoverAlpha = 0,
            padding = 2,
            perRow = 10,
            point = "BOTTOMLEFT,UIParent,BOTTOM,-216,152",
            showCount = true,
            showGrid = false,
            showHotkey = true,
            showMacro = true,
            size = 28,
            spacing = 2,
            visibility = "[vehicleui][overridebar][possessbar] hide; show",
        },
        tooltips = "enabled",
    },
    auras = {
        buffs = {
            enable = true,
            growthX = "LEFT",
            growthY = "UP",
            perRow = 10,
            point = "TOPRIGHT,UIParent,TOPRIGHT,-220,-8",
            rowSpacing = 14,
            rows = 2,
            showCount = true,
            showDuration = true,
            size = 30,
            spacing = 4,
        },
        debuffs = {
            enable = true,
            growthX = "LEFT",
            growthY = "DOWN",
            perRow = 8,
            point = "TOPRIGHT,UIParent,TOPRIGHT,-220,-150",
            rowSpacing = 14,
            rows = 1,
            showCount = true,
            showDuration = true,
            size = 32,
            spacing = 4,
        },
        enable = true,
    },
    chat = {
        alignToInfo = true,
        copyButton = true,
        editBoxTop = false,
        enable = true,
        fade = true,
        fadeAfter = 30,
        font = "Wick",
        fontOutline = "NONE",
        fontSize = 13,
        hideButtons = true,
        maxLines = 500,
        panel = true,
        panelAlpha = 0.5,
        tabFontSize = 12,
    },
    databars = {
        enable = true,
        hideAtMax = true,
        rep = {
            enable = true,
            height = 8,
            point = "BOTTOM,UIParent,BOTTOM,0,16",
            textOnHover = true,
            width = 420,
        },
        xp = {
            enable = true,
            height = 8,
            point = "BOTTOM,UIParent,BOTTOM,0,26",
            textOnHover = true,
            width = 420,
        },
    },
    datatexts = {
        backdrop = true,
        enable = true,
        fontSize = 18,
        panels = {
            left = {
                enable = true,
                height = 20,
                point = "BOTTOMLEFT,UIParent,BOTTOMLEFT,4,4",
                slots = "fps,durability,time",
                width = 420,
            },
            right = {
                enable = true,
                height = 20,
                point = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-4,4",
                slots = "gold,friends,bags",
                width = 420,
            },
            top = {
                enable = false,
                height = 20,
                point = "TOP,UIParent,TOP,0,-4",
                slots = "coords,zone,xp",
                width = 420,
            },
        },
    },
    extras = {
        afk = true,
        enable = true,
        markerPoint = "TOP,UIParent,TOP,0,-60",
        markerSize = 24,
        markerVertical = false,
        markerVisibility = "[group] show; hide",
        markers = true,
        quietErrors = true,
    },
    general = {
        brackets = true,
        classColors = true,
        edges = true,
        font = "Wick",
        fontOutline = "NONE",
        fontSize = 14,
        pixelPerfect = true,
        statusbar = "Wick Flat",
        -- Hologram's face runs large: its player name a size of its own.
        styleSizes = {
            hologram = {
                units = {
                    player = {
                        texts = {
                            left = 12,
                        },
                    },
                },
            },
        },
    },
    minimap = {
        clock = true,
        clock24 = true,
        clockLocal = true,
        clockSize = 12,
        collect = true,
        coords = true,
        coordsSize = 11,
        enable = true,
        fill = true,
        hideBlizzardText = true,
        hideZoom = true,
        mail = true,
        ring = false,
        square = false,
        zone = true,
        zoneInside = true,
        zoneSize = 12,
    },
    movers = {
        auras_buffs = "BOTTOMLEFT,UIParent,BOTTOMLEFT,389,321",
        auras_debuffs = "LEFT,UIParent,LEFT,441,-108",
        bar1 = "BOTTOM,UIParent,BOTTOM,0,36",
        bar3 = "BOTTOM,UIParent,BOTTOM,0,120",
        bar4 = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-456,36",
        bar5 = "BOTTOMLEFT,UIParent,BOTTOMLEFT,456,36",
        bar6 = "BOTTOM,UIParent,BOTTOM,0,78",
        castbar_player = "BOTTOM,UIParent,BOTTOM,0,342",
        petbar = "BOTTOMLEFT,UIParent,BOTTOMLEFT,547,163",
        stancebar = "BOTTOMLEFT,UIParent,BOTTOMLEFT,453,122",
        uf_boss = "RIGHT,UIParent,RIGHT,-339,100",
        uf_focus = "BOTTOM,UIParent,BOTTOM,-123,189",
        uf_party = "BOTTOM,UIParent,BOTTOM,65,256",
        uf_pet = "CENTER,UIParent,CENTER,-291,-68",
        uf_player = "BOTTOMLEFT,UIParent,BOTTOMLEFT,457,229",
        uf_target = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-505,228",
        uf_targettarget = "BOTTOM,UIParent,BOTTOM,105,190",
    },
    nameplates = {
        buffSize = 18,
        buffs = false,
        castHeight = 10,
        castIcon = true,
        castbar = true,
        clickThroughFriendly = true,
        debuffCount = 5,
        debuffSize = 22,
        debuffs = true,
        enable = true,
        execute = 0,
        executeColor = {
            [1] = 0.95,
            [2] = 0.25,
            [3] = 0.25,
            [4] = 1,
        },
        friendlyNameOnly = true,
        healthColor = "look",
        height = 14,
        levelShown = true,
        maxDistance = 41,
        nameSize = 14,
        nonTargetAlpha = 0.6,
        percent = true,
        percentSize = 10,
        quest = true,
        raidIcon = true,
        showFriends = false,
        stacking = true,
        targetBorder = true,
        targetScale = 1.2,
        threat = true,
        width = 112,
    },
    panelskins = {
        alpha = 0.95,
        brackets = true,
        buttons = true,
        enable = true,
        exclude = "",
        include = "ContainerFrameCombinedBags,ContainerFrame6,LFGParentFrame,BattlefieldMapFrame",
        mapPos = {
            [1] = 98.8443,
            [2] = 707.5568,
        },
        mapScale = 1,
        mapWindowed = true,
        moveWindows = true,
        tabs = true,
        windowPos = {},
    },
    skins = {
        bagsBar = "mouseover",
        damageMeter = true,
        enable = true,
        meterAlign = true,
        microMenu = "mouseover",
        tracker = true,
        trackerFontSize = 14,
    },
    tooltip = {
        anchor = "default",
        classBorder = true,
        cursorX = 20,
        cursorY = 20,
        enable = true,
        fontSize = 12,
        healthBar = true,
        hideUnitsInCombat = false,
        qualityBorder = true,
    },
    unitframes = {
        bgAlpha = 0.2,
        castColor = {
            [1] = 0.31,
            [2] = 0.78,
            [3] = 0.47,
            [4] = 1,
        },
        castLocked = {
            [1] = 0.45,
            [2] = 0.42,
            [3] = 0.5,
            [4] = 1,
        },
        classBackdrop = true,
        colorStrength = 0.85,
        darkColor = {
            [1] = 0.13,
            [2] = 0.12,
            [3] = 0.17,
            [4] = 1,
        },
        enable = true,
        font = "Wick",
        fontOutline = "OUTLINE",
        healthColor = "class",
        rangeAlpha = 0.45,
        smooth = true,
        targetBorder = true,
        threatBorder = true,
        units = {
            boss = {
                buffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HELPFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = false,
                    enable = true,
                    height = 14,
                    icon = true,
                    latency = false,
                    showName = true,
                    showTime = true,
                    width = 190,
                    x = 0,
                    y = -4,
                },
                classPower = false,
                combat = false,
                debuffs = {
                    anchor = "RIGHT",
                    attach = "LEFT",
                    enable = true,
                    filter = "HARMFUL",
                    growthX = "LEFT",
                    growthY = "UP",
                    onlyMine = true,
                    perRow = 5,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 24,
                    spacing = 2,
                    x = -4,
                    y = 0,
                },
                enable = true,
                height = 44,
                leader = true,
                phase = false,
                point = "RIGHT,UIParent,RIGHT,-120,120",
                portrait = "none",
                portraitWidth = 40,
                power = true,
                powerGap = 1,
                powerHeight = 8,
                raidIcon = true,
                rangeFade = false,
                readyCheck = false,
                resting = false,
                resurrect = false,
                role = false,
                spacing = 30,
                summon = false,
                texts = {
                    left = {
                        enable = true,
                        point = "LEFT",
                        size = 12,
                        tag = "[wui:namecolor][name]",
                        x = 4,
                        y = 0,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = true,
                        point = "RIGHT",
                        size = 12,
                        tag = "[wui:health]",
                        x = -4,
                        y = 0,
                    },
                },
                width = 190,
            },
            focus = {
                buffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HELPFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = false,
                    enable = true,
                    height = 16,
                    icon = true,
                    latency = false,
                    showName = true,
                    showTime = true,
                    width = 180,
                    x = 0,
                    y = -4,
                },
                classPower = false,
                combat = false,
                debuffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = true,
                    filter = "HARMFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = true,
                    perRow = 6,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 22,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                enable = true,
                height = 44,
                leader = true,
                phase = false,
                point = "LEFT,UIParent,LEFT,300,-100",
                portrait = "none",
                portraitWidth = 40,
                power = true,
                powerGap = 1,
                powerHeight = 8,
                raidIcon = true,
                rangeFade = false,
                readyCheck = false,
                resting = false,
                resurrect = false,
                role = false,
                summon = false,
                texts = {
                    left = {
                        enable = true,
                        point = "LEFT",
                        size = 12,
                        tag = "[wui:namecolor][name]",
                        x = 4,
                        y = 0,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = true,
                        point = "RIGHT",
                        size = 12,
                        tag = "[wui:health]",
                        x = -4,
                        y = 0,
                    },
                },
                width = 180,
            },
            focustarget = {
                buffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HELPFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = false,
                    enable = false,
                    height = 18,
                    icon = true,
                    latency = false,
                    showName = true,
                    showTime = true,
                    width = 220,
                    x = 0,
                    y = -4,
                },
                classPower = false,
                combat = false,
                debuffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HARMFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                enable = false,
                height = 34,
                leader = true,
                phase = false,
                point = "LEFT,UIParent,LEFT,490,-100",
                portrait = "none",
                portraitWidth = 40,
                power = false,
                powerGap = 1,
                powerHeight = 8,
                raidIcon = true,
                rangeFade = false,
                readyCheck = false,
                resting = false,
                resurrect = false,
                role = false,
                summon = false,
                texts = {
                    left = {
                        enable = true,
                        point = "CENTER",
                        size = 11,
                        tag = "[wui:namecolor][name]",
                        x = 0,
                        y = 0,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = false,
                        point = "RIGHT",
                        size = 11,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                },
                width = 120,
            },
            party = {
                buffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HELPFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = false,
                    enable = false,
                    height = 18,
                    icon = true,
                    latency = false,
                    showName = true,
                    showTime = true,
                    width = 220,
                    x = 0,
                    y = -4,
                },
                centerDebuff = true,
                centerSize = 22,
                classPower = false,
                combat = false,
                debuffs = {
                    anchor = "LEFT",
                    attach = "RIGHT",
                    enable = true,
                    filter = "HARMFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 4,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 22,
                    spacing = 2,
                    x = 4,
                    y = 0,
                },
                enable = true,
                growth = "RIGHT",
                height = 46,
                hotSize = 10,
                leader = true,
                myHots = true,
                phase = true,
                point = "LEFT,UIParent,LEFT,30,80",
                portrait = "none",
                portraitWidth = 40,
                power = true,
                powerGap = 1,
                powerHeight = 5,
                raidIcon = true,
                rangeFade = true,
                readyCheck = true,
                resting = false,
                resurrect = true,
                role = true,
                showPlayer = false,
                showSolo = false,
                sortBy = "ROLE",
                spacing = 2,
                summon = true,
                texts = {
                    left = {
                        enable = true,
                        point = "LEFT",
                        size = 12,
                        tag = "[wui:namecolor][name]",
                        x = 4,
                        y = 0,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = true,
                        point = "RIGHT",
                        size = 11,
                        tag = "[wui:deficit]",
                        x = -4,
                        y = 0,
                    },
                },
                visibility = "[@raid6,exists] hide; [group:party] show; hide",
                width = 117,
            },
            pet = {
                buffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HELPFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = false,
                    enable = false,
                    height = 18,
                    icon = true,
                    latency = false,
                    showName = true,
                    showTime = true,
                    width = 220,
                    x = 0,
                    y = -4,
                },
                classPower = false,
                combat = false,
                debuffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HARMFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                enable = true,
                height = 34,
                leader = true,
                phase = false,
                point = "BOTTOM,UIParent,BOTTOM,-300,160",
                portrait = "none",
                portraitWidth = 40,
                power = true,
                powerGap = 1,
                powerHeight = 5,
                raidIcon = true,
                rangeFade = false,
                readyCheck = false,
                resting = false,
                resurrect = false,
                role = false,
                summon = false,
                texts = {
                    left = {
                        enable = true,
                        point = "LEFT",
                        size = 11,
                        tag = "[name]",
                        x = 4,
                        y = 0,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = true,
                        point = "RIGHT",
                        size = 11,
                        tag = "[wui:perhp]",
                        x = -4,
                        y = 0,
                    },
                },
                width = 120,
            },
            player = {
                buffs = {
                    anchor = "TOPRIGHT",
                    attach = "TOP",
                    enable = false,
                    filter = "HELPFUL",
                    growthX = "LEFT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = true,
                    enable = true,
                    height = 22,
                    icon = true,
                    latency = true,
                    point = "BOTTOM,UIParent,BOTTOM,0,160",
                    showName = true,
                    showTime = true,
                    width = 260,
                    x = 0,
                    y = -4,
                },
                classPower = true,
                classPowerGap = 2,
                classPowerHeight = 6,
                classPowerX = 0,
                classPowerY = 3,
                combat = true,
                debuffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HARMFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                enable = true,
                height = 90,
                leader = true,
                phase = false,
                point = "BOTTOM,UIParent,BOTTOM,-300,210",
                portrait = "none",
                portraitWidth = 70,
                power = true,
                powerGap = 1,
                powerHeight = 12,
                raidIcon = true,
                rangeFade = false,
                readyCheck = false,
                resting = true,
                resurrect = true,
                role = true,
                summon = true,
                texts = {
                    left = {
                        enable = true,
                        point = "LEFT",
                        size = 18,
                        tag = "[wui:level] [wui:namecolor][name]",
                        x = 3,
                        y = -1,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = true,
                        point = "RIGHT",
                        size = 17,
                        tag = "[wui:health]",
                        x = -4,
                        y = 0,
                    },
                },
                width = 272,
            },
            raid = {
                buffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HELPFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = false,
                    enable = false,
                    height = 18,
                    icon = true,
                    latency = false,
                    showName = true,
                    showTime = true,
                    width = 220,
                    x = 0,
                    y = -4,
                },
                centerDebuff = true,
                centerSize = 22,
                classPower = false,
                columnGrowth = "RIGHT",
                columnSpacing = 4,
                combat = false,
                debuffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HARMFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                enable = true,
                groups = "1,2,3,4,5,6,7,8",
                growth = "DOWN",
                height = 44,
                hotSize = 10,
                leader = false,
                myHots = true,
                perColumn = 5,
                phase = true,
                point = "TOPLEFT,UIParent,TOPLEFT,30,-300",
                portrait = "none",
                portraitWidth = 40,
                power = true,
                powerGap = 1,
                powerHeight = 3,
                raidIcon = true,
                rangeFade = true,
                readyCheck = true,
                resting = false,
                resurrect = true,
                role = true,
                sortBy = "GROUP",
                spacing = 3,
                summon = true,
                texts = {
                    left = {
                        enable = true,
                        point = "TOP",
                        size = 11,
                        tag = "[wui:namecolor][name]",
                        x = 0,
                        y = -4,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = true,
                        point = "BOTTOM",
                        size = 10,
                        tag = "[wui:deficit]",
                        x = 0,
                        y = 6,
                    },
                },
                visibility = "[@raid6,exists] show; hide",
                width = 84,
            },
            target = {
                buffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = true,
                    filter = "HELPFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 27,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = false,
                    enable = true,
                    height = 18,
                    icon = true,
                    latency = false,
                    showName = true,
                    showTime = true,
                    width = 220,
                    x = 0,
                    y = -4,
                },
                classPower = false,
                combat = false,
                debuffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = true,
                    filter = "HARMFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 30,
                },
                enable = true,
                height = 86,
                leader = true,
                phase = false,
                point = "BOTTOM,UIParent,BOTTOM,300,210",
                portrait = "none",
                portraitWidth = 40,
                power = true,
                powerGap = 1,
                powerHeight = 8,
                raidIcon = true,
                rangeFade = false,
                readyCheck = false,
                resting = false,
                resurrect = false,
                role = false,
                summon = false,
                texts = {
                    left = {
                        enable = true,
                        point = "LEFT",
                        size = 16,
                        tag = "[wui:level] [wui:namecolor][name]",
                        x = 4,
                        y = 0,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = true,
                        point = "RIGHT",
                        size = 12,
                        tag = "[wui:health]",
                        x = -4,
                        y = 0,
                    },
                },
                width = 214,
            },
            targettarget = {
                buffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HELPFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                castbar = {
                    detach = false,
                    enable = false,
                    height = 18,
                    icon = true,
                    latency = false,
                    showName = true,
                    showTime = true,
                    width = 220,
                    x = 0,
                    y = -4,
                },
                classPower = false,
                combat = false,
                debuffs = {
                    anchor = "TOPLEFT",
                    attach = "TOP",
                    enable = false,
                    filter = "HARMFUL",
                    growthX = "RIGHT",
                    growthY = "UP",
                    onlyMine = false,
                    perRow = 8,
                    rows = 1,
                    showCount = true,
                    showDuration = true,
                    size = 26,
                    spacing = 2,
                    x = 0,
                    y = 4,
                },
                enable = true,
                height = 34,
                leader = true,
                phase = false,
                point = "BOTTOM,UIParent,BOTTOM,300,160",
                portrait = "none",
                portraitWidth = 40,
                power = false,
                powerGap = 1,
                powerHeight = 8,
                raidIcon = true,
                rangeFade = false,
                readyCheck = false,
                resting = false,
                resurrect = false,
                role = false,
                summon = false,
                texts = {
                    left = {
                        enable = true,
                        point = "CENTER",
                        size = 11,
                        tag = "[wui:namecolor][name]",
                        x = 0,
                        y = 0,
                    },
                    power = {
                        enable = false,
                        point = "RIGHT",
                        size = 10,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                    right = {
                        enable = false,
                        point = "RIGHT",
                        size = 11,
                        tag = "",
                        x = -4,
                        y = 0,
                    },
                },
                width = 144,
            },
        },
    },
}

local OPEN = { movers = true, styleSizes = true }

local function over(dst, src, open)
    for k, v in pairs(src) do
        if type(v) == "table" then
            if open or OPEN[k] then
                dst[k] = ns:Copy(v)
            elseif type(dst[k]) == "table" then
                over(dst[k], v, false)
            end
        elseif open or dst[k] ~= nil then
            dst[k] = v
        end
    end
end

-- Bars and units are keyed tables the defaults fill in, so those are
-- walked like any other.
function ns:ApplyDefaultLayout()
    over(ns.defaults.profile, LAYOUT, false)
end
ns.DEFAULT_LAYOUT = LAYOUT
ns:ApplyDefaultLayout()
